### ISSUE TITLE
isSpeaking state not working with WebRTC connection type

### ISSUE THREAD

**Issue by roke77** [elevenlabs/packages#111]
I just updated to 0.3.0 and tried the new `connectionType : 'webrtc'` and noticed that the `isSpeaking` state we use for animating an avatar is not working as with websockets.

**Comment by jhobz23** [comment]
> I just updated to 0.3.0 and tried the new `connectionType : 'webrtc'` and noticed that the `isSpeaking` state we use for animating an avatar is not working as with websockets.

I can confirm this one, `isSpeaking` does not work when using `'webrtc'`.

**Comment by PaulAsjes** [comment]
Thanks for the report, I'll be looking into this this week.

**Comment by PaulAsjes** [comment]
Fixed in v0.4.1!

**Comment by efjaycz** [comment]
Hi @PaulAsjes I just tried `mute` again, but without success. The mic is still not muted, I tried to log out the `micMuted` and it returns `true`, but the agent still hears me talking. Tested with Czech language, model Flash v2.5. and Hope - natural conversation voice. If you need more info let me know.

**Comment by PaulAsjes** [comment]
@efjaycz can you share how you're muting the mic? This works for me:

```ts
const [micMuted, setMicMuted] = useState(false);
const conversation = useConversation({
  micMuted,
});

const toggleMute = useCallback(() => {
  setMicMuted(!micMuted);
}, [micMuted]);
...

**Comment by efjaycz** [comment]
Yeah sure:

```
const [micMuted, setMicMuted] = useState(false);
const conversation = useConversation({
  agentId: voicebotAgentId,
  micMuted,
  onConnect:...
  onMessage:...
  onDisconnect:...
});

<Button
   onClick={() => setMicMuted((value) => !value)}
/>
```

**Comment by PaulAsjes** [comment]
Can you try using React's `useCallback` hook like in my example and see if that works?
